version: '3'
services:
  asistent:
    mem_limit: 2048m
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./src:/usr/src/app/src
    depends_on:
      - db
      - vtt-vosk-service
      - tts-piper-service
  db:
    restart: always
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  vtt-vosk-service:
    mem_limit: 5120m
    restart: always
#    image: alphacep/kaldi-ru:latest
    build:
        context: .
        dockerfile: vosk.Dockerfile
    ports:
      - "2700:2700"
    volumes:
      - ./voskdata:/opt/samples
  tts-piper-service:
    mem_limit: 2048m
    restart: always
    build:
      context: .
      dockerfile: piper.Dockerfile
    ports:
      - "5002:5002"
    volumes:
      - ./piper/src/piper-server:/usr/src/piper/src/piper-server
      - ./piper/models:/usr/src/piper/models
